version: '2'
services:
  webserver:
    image: nginx:ver1
    container_name: nginx
    ports:
      - "8080:80"
    links:
      - app:php72-fpm
      - db:mysql
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx/
      - ./php72-fpm/socket/:/var/run/php-fpm/ # ここ大事。app:php72のボリュームを共有するんだよ
    depends_on:
      - app

  app:
    image: php7.2:ver1
    container_name: php72
    volumes:
      - ./html:/usr/share/nginx/html
      - ./php72-fpm/config/php.ini:/usr/local/etc/php/php.ini
      #- ./php72-fpm/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php72-fpm/config/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./php72-fpm/socket/:/var/run/php-fpm/
      - ./php72-fpm/log:/usr/local/var/log/

    #env_file: ./mysql/env/.env
    #environment:
    #  DATABASE_HOST: db
    links:
      - db:mysql
    depends_on:
      - db

  db:
    image: mysql:ver1
    container_name: mysql
    env_file:
      - ./mysql/env/mysql.env
    #environment:
      #MYSQL_ROOT_PASSWORD: password
      #MYSQL_USER: docker
      #MYSQL_PASSWORD: password
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #TZ: Asia/Tokyo
    ports:
      - "3333:3306"
    volumes:
      - ./mysql/databases/wordpress:/var/lib/mysql/wordpress
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf





